import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import Lottie from 'react-lottie';
import animationData from '../svg/QI_logo_ani_SVG(1280*800).json';

import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import styles from '../styles/Home.module.css';

const Homepage = () => {
	const { t } = useTranslation('common');

	const defaultOptions = {
		loop: true,
		autoplay: true,
		animationData: animationData,
		rendererSettings: {
			preserveAspectRatio: 'xMidYMid slice',
		},
	};

	return (
		<div>
			<Head>
				<title>Quantinum Investment</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="keywords" content="퀀티넘, 투자자문, 인베스트먼트, 부동산투자" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>{t('test')}</h1>

			<Lottie options={defaultOptions} height={800} width={1280} />
		</div>
	);
};

// export const getServerSideProps = async ({ locale }) => ({
export const getStaticProps = async ({ locale }) => ({
	props: {
		...(await serverSideTranslations(locale, ['common', 'footer'])),
	},
});

export default Homepage;
