import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { useRouter } from 'next/router';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import styles from '../styles/Home.module.css';

const Homepage = () => {
	const router = useRouter();
	const { t } = useTranslation('common');

	const changeTo = router.locale === 'en' ? 'ko' : 'en';

	return (
		<div>
			<Head>
				<title>Quantinum Investment</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="keywords" content="퀀티넘, 투자자문, 인베스트먼트, 부동산투자" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>{t('test')}</h1>

			<Link href="/" locale={changeTo}>
				<a>{t('change-locale', { changeTo })}</a>
			</Link>
		</div>
	);
};

// export const getServerSideProps = async ({ locale }) => ({
export const getStaticProps = async ({ locale }) => ({
	props: {
		...(await serverSideTranslations(locale, ['common', 'footer'])),
	},
});

export default Homepage;
